"""Data models for serendipity recommendations."""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Recommendation:
    """A single recommendation with optional rich metadata.

    Supports both simple (url, reason) format for backwards compatibility
    and extended format with type-specific metadata.
    """
    url: str
    reason: str

    # Recommendation categorization
    approach: str = "convergent"  # convergent, divergent, etc.
    media_type: str = "article"   # youtube, book, article, podcast, etc.

    # Common optional fields
    title: Optional[str] = None
    thumbnail_url: Optional[str] = None

    # Type-specific metadata stored as dict
    # Examples:
    #   youtube: {channel, duration, views}
    #   book: {author, year, publisher}
    #   article: {publication, read_time, excerpt}
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        result = {
            "url": self.url,
            "reason": self.reason,
            "approach": self.approach,
            "media_type": self.media_type,
        }
        if self.title:
            result["title"] = self.title
        if self.thumbnail_url:
            result["thumbnail_url"] = self.thumbnail_url
        if self.metadata:
            result["metadata"] = self.metadata
        return result

    @classmethod
    def from_dict(cls, data: dict, approach: str = "convergent") -> "Recommendation":
        """Create from dictionary, handling both simple and extended formats."""
        return cls(
            url=data.get("url", ""),
            reason=data.get("reason", ""),
            approach=data.get("approach", approach),
            media_type=data.get("type", data.get("media_type", "article")),
            title=data.get("title"),
            thumbnail_url=data.get("thumbnail_url"),
            metadata=data.get("metadata", {}),
        )


@dataclass
class HtmlStyle:
    """HTML styling generated by Claude."""
    description: str
    css: str
